# Generated by Django 4.1.1 on 2022-10-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="money", name="money", field=models.IntegerField(),
        ),
    ]
